"use strict";
let num1 = 10;
let num2 = 5;
let num3;
num3 = num1 + num2;
console.log("Tổng:", num3);
num3 = num1 - num2;
console.log("Hiệu:", num3);
num3 = num1 * num2;
console.log("Tích:", num3);
num3 = num1 / num2;
console.log("Thương:", num3);
num1 = "10";
num2 = true;
num3 = num1 + num2;
console.log("Tổng sau khi thay đổi kiểu:", num3);
num3 = num1 - num2;
console.log("Hiệu sau khi thay đổi kiểu:", num3);
num3 = num1 * num2;
console.log("Tích sau khi thay đổi kiểu:", num3);
num3 = num1 / num2;
console.log("Thương sau khi thay đổi kiểu:", num3);
